app/routes/buscador.py
from app.utils.helpers import login_required, verificar_formulario_completo
from flask import Blueprint, render_template, request, session, jsonify
from app.utils.conexion import conexion_basedatos


buscador_bp = Blueprint('buscar', __name__)


# Ruta de Buscador
@buscador_bp.route('/buscador', methods=['GET'])
@login_required
@verificar_formulario_completo
def buscador():
    query = request.args.get('query', '')  # Filtro general
    tipo = request.args.get('tipo', '')    # Filtro por rol
    pais = request.args.get('pais', '')    # Filtro por país
    sexo = request.args.get('sexo', '')    # Filtro por sexo

    connection = conexion_basedatos()
    cursor = connection.cursor()

    # Consulta para realizar la búsqueda general y aplicar filtros
    base_query = """
        SELECT u.id_usuario, u.nombre_usuario, u.rol, 
               a.nombre, a.apellido, a.foto_perfil, p_a.nombre as pais_alumno, p_a.codigo_iso as iso_alumno, a.sexo as sexo_alumno,
               e.nombre, e.apellido, e.foto_perfil, p_e.nombre as pais_entrenador, p_e.codigo_iso as iso_entrenador, e.sexo as sexo_entrenador
        FROM usuario u
        LEFT JOIN alumno a ON u.id_usuario = a.id_usuario
        LEFT JOIN pais p_a ON a.id_pais = p_a.id_pais
        LEFT JOIN entrenador e ON u.id_usuario = e.id_usuario
        LEFT JOIN pais p_e ON e.id_pais = p_e.id_pais
        WHERE (u.nombre_usuario LIKE ? OR 
               a.nombre LIKE ? OR a.apellido LIKE ? OR p_a.nombre LIKE ? OR
               e.nombre LIKE ? OR e.apellido LIKE ? OR p_e.nombre LIKE ?)
    """
    filters = ['%' + query + '%'] * 7  # Parámetros para la búsqueda general

    # Aplicar filtros adicionales
    if tipo:
        base_query += " AND u.rol = ?"
        filters.append(tipo)
    if pais:
        # Buscar país tanto para alumnos como para entrenadores
        base_query += " AND (a.id_pais = ? OR e.id_pais = ?)"
        filters.extend([pais, pais])
    if sexo:
        # Buscar sexo tanto para alumnos como para entrenadores
        base_query += " AND (a.sexo = ? OR e.sexo = ?)"
        filters.extend([sexo, sexo])

    cursor.execute(base_query, filters)
    resultados = cursor.fetchall()

    # Obtener lista de países para el filtro
    cursor.execute("SELECT id_pais, nombre FROM pais")
    paises = cursor.fetchall()

    cursor.execute("SELECT id_pais, codigo_iso FROM pais")
    paises_iso = cursor.fetchall()

    connection.close()

    # Renderizar la plantilla
    return render_template(
        'buscador.html',
        query=query,
        tipo=tipo,
        pais=pais,
        sexo=sexo,
        resultados=resultados,
        paises=paises,
        paises_iso=paises_iso,
        rol=session.get('rol')
    )


# Ruta para obtener los datos de un usuario
@buscador_bp.route('/datos_usuario/<int:id_usuario>', methods=['GET'])
@login_required
def obtener_datos_usuario(id_usuario):
    connection = conexion_basedatos()
    cursor = connection.cursor()

    # Consultar la tabla usuario
    cursor.execute("""
        SELECT u.email, u.nombre_usuario, u.rol
        FROM usuario u
        WHERE u.id_usuario = ?
    """, (id_usuario,))
    usuario = cursor.fetchone()

    if not usuario:
        connection.close()
        return jsonify({'error': 'Usuario no encontrado'}), 404

    # Si el usuario es un alumno
    if usuario[2] == 1:
        cursor.execute("""
            SELECT a.nombre, a.apellido, a.id_pais, a.sexo, a.biografia, a.foto_perfil, a.instagram, a.facebook, a.telefono
            FROM alumno a
            WHERE a.id_usuario = ?
        """, (id_usuario,))
        alumno = cursor.fetchone()

        if alumno:
            cursor.execute("""
                SELECT p.nombre
                FROM pais p
                WHERE p.id_pais = ?
            """, (alumno[2],))
            pais = cursor.fetchone()

            datos_usuario = {
                'email': usuario[0],
                'nombre_usuario': usuario[1],
                'rol': usuario[2],
                'nombre': alumno[0],
                'apellido': alumno[1],
                'id_pais': pais[0] if pais else None,
                'sexo': alumno[3],
                'biografia': alumno[4],
                'foto_perfil': alumno[5],
                'instagram': alumno[6],
                'facebook': alumno[7],
                'telefono': alumno[8]
            }
            connection.close()
            return jsonify(datos_usuario)

    # Si el usuario es un entrenador
    elif usuario[2] == 2:
        cursor.execute("""
            SELECT e.nombre, e.apellido, e.especializacion, e.experiencia, e.foto_perfil, e.instagram, e.facebook, e.telefono
            FROM entrenador e
            WHERE e.id_usuario = ?
        """, (id_usuario,))
        entrenador = cursor.fetchone()

        if entrenador:
            datos_usuario = {
                'email': usuario[0],
                'nombre_usuario': usuario[1],
                'rol': usuario[2],
                'nombre': entrenador[0],
                'apellido': entrenador[1],
                'especializacion': entrenador[2],
                'experiencia': entrenador[3],
                'foto_perfil': entrenador[4],
                'instagram': entrenador[5],
                'facebook': entrenador[6],
                'telefono': entrenador[7]
            }
            connection.close()

            return jsonify(datos_usuario)
        
    connection.close()
    return jsonify({'error': 'Datos no encontrados'}), 404

app/routes/notificaciones.py
from flask import Blueprint, render_template, request, session, redirect, flash, url_for
from app.utils.conexion import conexion_basedatos
from app.utils.helpers import login_required
from datetime import datetime
import secrets


notificaciones_bp = Blueprint('notificaciones', __name__)


# Ruta de Enviar Solicitud
@notificaciones_bp.route('/enviar_solicitud/<int:id_usuario_destino>', methods=['POST'])
@login_required
def enviar_solicitud(id_usuario_destino):
    id_usuario_origen = session['id_usuario']

    try:
        # Verificar que el origen sea un entrenador
        conexion = conexion_basedatos()
        cursor = conexion.cursor()
        
        cursor.execute("""
            SELECT rol FROM usuario WHERE id_usuario = ?
        """, (id_usuario_origen,))
        rol_origen = cursor.fetchone()

        if rol_origen[0] != 2:
            flash("Solo los entrenadores pueden enviar solicitudes.", "error")
            return redirect(url_for('usuario.usuario', id_usuario=id_usuario_origen))

        # Generar un token único
        token = secrets.token_urlsafe(16)

        # Generar la fecha y hora
        fecha_actual = datetime.now().strftime("%Y-%m-%d %H:%M")

        # Insertar en la tabla vinculaciones
        cursor.execute("""
            INSERT INTO vinculaciones (id_usuario_origen, id_usuario_destino, estado, token, fecha_solicitud)
            VALUES (?, ?, 'pendiente', ?, ?)
        """, (id_usuario_origen, id_usuario_destino, token, fecha_actual))

        conexion.commit()
        conexion.close()

        flash("Solicitud de conexión enviada correctamente.", "success")
        return redirect(url_for('usuario.usuario', id_usuario=id_usuario_destino))

    except Exception as e:
        flash("Error al enviar la solicitud. Intente nuevamente.", "error")

        return redirect(url_for('usuario.usuario', id_usuario=id_usuario_origen))


# Ruta para cancelar una solicitud pendiente
@notificaciones_bp.route('/cancelar_solicitud/<int:id_usuario_destino>', methods=['POST'])
@login_required
def cancelar_solicitud(id_usuario_destino):
    id_usuario_origen = session['id_usuario']

    try:
        conexion = conexion_basedatos()
        cursor = conexion.cursor()

        # Verificar que existe una solicitud pendiente
        cursor.execute("""
            DELETE FROM vinculaciones
            WHERE id_usuario_origen = ? AND id_usuario_destino = ? AND estado = 'pendiente'
        """, (id_usuario_origen, id_usuario_destino))

        conexion.commit()
        conexion.close()

        flash("Solicitud cancelada correctamente.", "success")
        return redirect(url_for('usuario.usuario', id_usuario=id_usuario_destino))

    except Exception as e:
        print(f"Error al cancelar solicitud: {e}")
        flash("Error al cancelar la solicitud.", "error")
        return redirect(url_for('usuario.usuario', id_usuario=id_usuario_origen))


# Ruta para eliminar una conexión existente
@notificaciones_bp.route('/eliminar_conexion/<int:id_usuario_destino>', methods=['POST'])
@login_required
def eliminar_conexion(id_usuario_destino):
    id_usuario_origen = session['id_usuario']

    try:
        conexion = conexion_basedatos()
        cursor = conexion.cursor()

        # Eliminar la conexión aceptada
        cursor.execute("""
            DELETE FROM vinculaciones
            WHERE id_usuario_origen = ? AND id_usuario_destino = ? AND estado = 'aceptada'
        """, (id_usuario_origen, id_usuario_destino))

        # Crear notificación para el alumno
        cursor.execute("""
            SELECT nombre_usuario FROM usuario WHERE id_usuario = ?
        """, (id_usuario_origen,))
        nombre_entrenador = cursor.fetchone()[0]

        mensaje = f"El entrenador @{nombre_entrenador} ha eliminado tu conexión."
        cursor.execute("""
            INSERT INTO notificaciones (id_usuario, mensaje)
            VALUES (?, ?)
        """, (id_usuario_destino, mensaje))

        conexion.commit()
        conexion.close()

        flash("Conexión eliminada correctamente.", "success")
        return redirect(url_for('usuario.usuario', id_usuario=id_usuario_destino))

    except Exception as e:
        print(f"Error al eliminar conexión: {e}")
        flash("Error al eliminar la conexión.", "error")
        return redirect(url_for('usuario.usuario', id_usuario=id_usuario_origen))


# Ruta para listar las solicitudes pendientes
@notificaciones_bp.route('/notificaciones', methods=['GET'])
@login_required
def listar_solicitudes():
    id_usuario = session['id_usuario']
    orden = request.args.get('orden', default='desc', type=str)  # Nuevo: obtener parámetro de orden

    conexion = conexion_basedatos()
    cursor = conexion.cursor()

    # Obtener solicitudes pendientes
    cursor.execute("""
        SELECT v.id_vinculacion, u.nombre_usuario, v.fecha_solicitud 
        FROM vinculaciones v
        JOIN usuario u ON v.id_usuario_origen = u.id_usuario
        WHERE v.id_usuario_destino = ? AND v.estado = 'pendiente'
        ORDER BY v.fecha_solicitud DESC
    """, (id_usuario,))
    solicitudes = cursor.fetchall()

    # Obtener notificaciones con ordenamiento dinámico
    order_clause = "DESC" if orden == 'desc' else "ASC"  # Determinar el orden
    cursor.execute(f"""
        SELECT id_notificacion, mensaje, fecha, id_entrenamiento
        FROM notificaciones
        WHERE id_usuario = ?
        ORDER BY fecha {order_clause}
    """, (id_usuario,))
    notificaciones = cursor.fetchall()

    conexion.close()

    # Formatear solicitudes pendientes
    solicitudes_formateadas = []
    for solicitud in solicitudes:
        solicitudes_formateadas.append({
            'id_vinculacion': solicitud[0],
            'nombre_usuario': solicitud[1],
            'fecha_solicitud': datetime.strptime(solicitud[2], "%Y-%m-%d %H:%M").strftime("%d/%m/%Y - %H:%M")
        })

    # Formatear notificaciones
    notificaciones_formateadas = []
    for notificacion in notificaciones:
        notificaciones_formateadas.append({
            'id_notificacion': notificacion[0],
            'mensaje': notificacion[1],
            'fecha': datetime.strptime(notificacion[2], "%Y-%m-%d %H:%M:%S").strftime("%d/%m/%Y - %H:%M"),
            'id_entrenamiento': notificacion[3]
        })

    return render_template(
        'notificaciones.html',
        solicitudes=solicitudes_formateadas,
        notificaciones=notificaciones_formateadas,
        orden_actual=orden
    )


# Ruta para responder a una solicitud
@notificaciones_bp.route('/responder_solicitud/<int:id_vinculacion>', methods=['POST'])
@login_required
def responder_solicitud(id_vinculacion):
    respuesta = request.form.get('respuesta')
    id_usuario_destino = session['id_usuario']

    try:
        conexion = conexion_basedatos()
        cursor = conexion.cursor()

        # Obtener los datos de la vinculación
        cursor.execute("""
            SELECT id_usuario_origen, id_usuario_destino, estado 
            FROM vinculaciones 
            WHERE id_vinculacion = ? AND id_usuario_destino = ?
        """, (id_vinculacion, id_usuario_destino))
        resultado = cursor.fetchone()

        if not resultado:
            flash("Solicitud no encontrada.", "error")
            return redirect(url_for('notificaciones.listar_solicitudes'))

        id_usuario_origen = resultado[0]
        estado_actual = resultado[2]

        if estado_actual != 'pendiente':
            flash("Esta solicitud ya fue procesada.", "error")
            return redirect(url_for('notificaciones.listar_solicitudes'))

        if respuesta == 'aceptar':
            # Actualizar el estado a 'aceptada'
            cursor.execute("""
                UPDATE vinculaciones
                SET estado = 'aceptada'
                WHERE id_vinculacion = ?
            """, (id_vinculacion,))

            # Notificación para el entrenador
            cursor.execute("""
                SELECT nombre_usuario FROM usuario WHERE id_usuario = ?
            """, (id_usuario_destino,))
            nombre_alumno = cursor.fetchone()[0]

            mensaje = f"El usuario @{nombre_alumno} ha aceptado tu solicitud de conexión."
            cursor.execute("""
                INSERT INTO notificaciones (id_usuario, mensaje)
                VALUES (?, ?)
            """, (id_usuario_origen, mensaje))

            flash("Solicitud aceptada exitosamente.", "success")

        elif respuesta == 'rechazar':
            # Actualizar el estado a 'rechazada'
            cursor.execute("""
                UPDATE vinculaciones
                SET estado = 'rechazada'
                WHERE id_vinculacion = ?
            """, (id_vinculacion,))

            # Notificación para el entrenador
            cursor.execute("""
                SELECT nombre_usuario FROM usuario WHERE id_usuario = ?
            """, (id_usuario_destino,))
            nombre_alumno = cursor.fetchone()[0]

            mensaje = f"El usuario @{nombre_alumno} ha rechazado tu solicitud de conexión."
            cursor.execute("""
                INSERT INTO notificaciones (id_usuario, mensaje)
                VALUES (?, ?)
            """, (id_usuario_origen, mensaje))

            flash("Solicitud rechazada exitosamente.", "success")

        conexion.commit()
        conexion.close()
        return redirect(url_for('notificaciones.listar_solicitudes'))

    except Exception as e:
        print(f"Error al procesar la solicitud: {e}")
        flash("Error al procesar la solicitud.", "error")
        return redirect(url_for('notificaciones.listar_solicitudes'))


# Ruta para eliminar todas las notificaciones
@notificaciones_bp.route('/eliminar_notificaciones', methods=['POST'])
@login_required
def eliminar_notificaciones():
    tipo = request.form.get('tipo')
    id_usuario = session['id_usuario']

    try:
        conexion = conexion_basedatos()
        cursor = conexion.cursor()

        # Eliminar notificaciones
        cursor.execute("""

app/routes/suscripcion.py
from flask import Blueprint, render_template, request, redirect, url_for, session, flash
from app.utils.helpers import login_required
from app.utils.conexion import conexion_basedatos
from datetime import date, timedelta


suscripcion_bp = Blueprint('suscripcion', __name__)


def confirmar_suscripcion():
    try:
        # Obtener el ID del usuario de la sesión
        id_usuario = session.get('id_usuario')
        rol = session.get('rol')
        
        # Verificar que el usuario es un entrenador
        if rol != 2:
            flash('Solo los entrenadores pueden suscribirse', 'error')
            return redirect(url_for('suscripcion.suscripcion'))

        # Obtener fechas
        fecha_actual = date.today()
        fecha_fin = fecha_actual + timedelta(days=30)  # 1 mes de suscripción

        # Actualizar la base de datos
        conn = conexion_basedatos()
        cursor = conn.cursor()
        
        cursor.execute("""
            UPDATE usuario 
            SET fecha_inicio_suscripcion = ?, 
                fecha_fin_suscripcion = ?, 
                estado_suscripcion = 1 
            WHERE id_usuario = ?
        """, (fecha_actual, fecha_fin, id_usuario))
        
        conn.commit()
        conn.close()

        # Actualizar la sesión
        session['estado_suscripcion'] = 1
        flash('Suscripción confirmada con éxito', 'success')
        
        # Redirigir al dashboard
        return redirect(url_for('entrenamiento.entrenamiento'))
    
    except Exception as e:
        flash(f'Error al confirmar la suscripción: {str(e)}', 'error')
        return redirect(url_for('suscripcion.suscripcion'))
    

# Ruta de Entrenamiento
@suscripcion_bp.route('/suscripcion', methods=['GET', 'POST'])
@login_required
def suscripcion():
    if request.method == 'POST':
        # Procesar la confirmación de suscripción
        return confirmar_suscripcion()
    
    # Obtener paises para el formulario
    conn = conexion_basedatos()
    cursor = conn.cursor()
    cursor.execute("SELECT id_pais, nombre FROM pais")
    paises = cursor.fetchall()
    conn.close()


    return render_template('suscripcion.html', paises=paises)

app/templates/buscador.html
{% extends 'base.html' %}

{% block title %}
    Resultados de Búsqueda - Training+
{% endblock %}

{% block content %}

<!-- Título y Filtros -->
<div class="title" title="Sección de resultados de búsqueda">
    <h1 data-aos="fade-right" title="Encabezado de resultados">Resultados de Búsqueda</h1>
    <p data-aos="fade-right" title="Descripción de la búsqueda">Filtra los resultados para una búsqueda más precisa.</p>
    <form class="filters-container" method="get" action="{{ url_for('buscar.buscador') }}" title="Formulario para filtrar resultados">
        <input type="hidden" name="query" value="{{ query }}" title="Consulta de búsqueda actual">
        
        <select name="tipo" id="tipo" onchange="this.form.submit()" data-aos="fade-in" data-aos-delay="100" title="Filtra por tipo de usuario">
            <option value="" title="Mostrar todos los tipos">Filtrar por Tipo</option>
            <option value="2" {% if request.args.get('tipo') == '2' %}selected{% endif %} title="Mostrar solo entrenadores">Entrenador</option>
            <option value="1" {% if request.args.get('tipo') == '1' %}selected{% endif %} title="Mostrar solo usuarios">Usuario</option>
        </select>
        
        <select name="pais" id="pais" onchange="this.form.submit()" data-aos="fade-in" data-aos-delay="200" title="Filtra por país de origen">
            <option value="" title="Mostrar todos los países">Filtrar por País</option>
            {% for pais in paises %}
                <option value="{{ pais.id_pais }}" {% if request.args.get('pais') == pais.id_pais|string %}selected{% endif %} title="Filtrar por {{ pais.nombre }}">{{ pais.nombre }}</option>
            {% endfor %}
        </select>
        
        <select name="sexo" id="sexo" onchange="this.form.submit()" data-aos="fade-in" data-aos-delay="300" title="Filtra por género">
            <option value="" title="Mostrar todos los géneros">Filtrar por Género</option>
            <option value="masculino" {% if request.args.get('sexo') == 'masculino' %}selected{% endif %} title="Mostrar solo masculino">Masculino</option>
            <option value="femenino" {% if request.args.get('sexo') == 'femenino' %}selected{% endif %} title="Mostrar solo femenino">Femenino</option>
        </select>
    </form>
</div>

<!-- Mostrar Resultados -->
{% if resultados %}
    {% for id_usuario, nombre_usuario, rol, nombre, apellido, foto_perfil, pais_alumno, iso_alumno, sexo_alumno, nombre_entrenador, apellido_entrenador, foto_entrenador, pais_entrenador, iso_entrenador, sexo_entrenador in resultados %}
    <div class="results-container open-modal" id="open-modal" data-id="{{ id_usuario }}" data-aos="fade-right" data-aos-delay="100" title="Haz clic para ver el perfil de este usuario">
        <div class="user-data" title="Datos del usuario encontrado">
            <div class="photo" title="Foto de perfil del usuario">
                {% if rol == 1 %}
                    <img src="{{ url_for('static', filename='uploads/users/' + (foto_perfil or 'profile.webp')) }}" alt="Foto de Perfil" title="Foto de usuario">
                {% else %}
                    <img src="{{ url_for('static', filename='uploads/users/' + (foto_entrenador or 'profile.webp')) }}" alt="Foto de Perfil" title="Foto de entrenador">
                {% endif %}
            </div>
            <div class="user" title="Información del usuario">
                {% if rol == 1 %}
                    <h2 title="Nombre y apellido del usuario">{{ nombre|upper }} {{ apellido|upper }} 
                        <i class="bx bx-user" title="Icono de usuario"></i>
                    </h2>
                    <p title="Nombre de usuario">@{{ nombre_usuario }}</p>
                    {% if pais_alumno %}
                        <p title="País de origen">{{ pais_alumno }}</p>
                    {% endif %}
                {% else %}
                    <h2 title="Nombre y apellido del entrenador">{{ nombre_entrenador|upper }} {{ apellido_entrenador|upper }} 
                        <i class="bx bx-medal" title="Icono de entrenador"></i>
                    </h2>
                    <p title="Nombre de usuario">@{{ nombre_usuario }}</p>
                    {% if pais_entrenador %}
                        <p title="País de origen">{{ pais_entrenador }}</p>
                    {% endif %}
                {% endif %}
            </div>
            <i class='bx bx-chevron-right open-profile' title="Ver perfil completo"></i>
        </div>
    </div>
    {% endfor %}
{% else %}
    <div class="results-container" title="No se encontraron resultados">
        <p title="Mensaje de búsqueda vacía">No se encontraron resultados para "{{ query }}".</p>
    </div>
{% endif %}

<script>
    document.addEventListener('DOMContentLoaded', () => {
        const userDivs = document.querySelectorAll('.results-container');

        userDivs.forEach(div => {
            div.addEventListener('click', () => {
                const userId = div.getAttribute('data-id');
                if (userId) {
                    // Redirige a la ruta del usuario
                    window.location.href = `/usuario/${userId}`;
                }
            });
        });
    });
</script>

{% endblock %}

app/templates/notificaciones.html
{% extends 'base.html' %}

{% block title %}
    Notificaciones - Training+
{% endblock %}

{% block content %}
    <div class="notificactions-title">
        <h1 data-aos="fade-right" title="Listado de tus notificaciones">Tus Notificaciones</h1>
        <p data-aos="fade-right" data-aos-delay="100" title="Aquí puedes visualizar y gestionar tus notificaciones">Visualiza y gestiona tus notificaciones para mantenerte al día.</p>
    </div>

    <!-- Mensajes Flash -->
    {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            <ul class="flash-messages" title="Mensajes informativos y de error">
                {% for category, message in messages %}
                    <li class="flash {{ category }}" title="{{ 'Error' if category == 'error' else 'Éxito' }}: {{ message }}">
                        <i class="{{ 'bx bxs-error-circle' if category == 'error' else 'bx bxs-check-circle' }}" title="Icono de estado"></i>
                        {{ message }}
                    </li>
                {% endfor %}
            </ul>
        {% endif %}
    {% endwith %}

    <div class="notifications-container">
        <!-- Filtros y Eliminar -->
        <div class="notifications-sections section-filter" data-aos="flip-right" data-aos-delay="200">
            <h2 data-aos="fade-right" data-aos-delay="300" title="Filtrar notificaciones">Filtros</h2>

            <form id="filtro-form" data-aos="fade-right" data-aos-delay="300">
                <select name="orden" id="orden-notificaciones" title="Ordenar notificaciones por fecha">
                    <option value="desc" {% if orden_actual=='desc' %}selected{% endif %}>Más Recientes</option>
                    <option value="asc" {% if orden_actual=='asc' %}selected{% endif %}>Más Antiguas</option>
                </select>
            </form>

            <form action="{{ url_for('notificaciones.eliminar_notificaciones') }}" class="eliminar-notificaciones-form" method="POST" data-aos="fade-right" data-aos-delay="300">
                <button type="submit" title="Eliminar todas las notificaciones">Eliminar Notificaciones</button>
            </form>
        </div>

        <!-- Notificaciones -->
        <div class="notifications-sections section-notificaction" data-aos="flip-left" data-aos-delay="200">
            {% for solicitud in solicitudes %}
                <ul class="notificacion" title="Solicitud de conexión de entrenador">
                    <li data-aos="fade-down" data-aos-delay="300">
                        <h3 title="Solicitud de conexión"><i class='bx bxs-group' title="Icono de grupo"></i> Solicitud de Conexión</h3>
                        <div class="message" title="Mensaje de solicitud">
                            <strong title="Nombre del entrenador solicitante">El entrenador @<a href="#" title="Ver perfil del entrenador">{{ solicitud['nombre_usuario'] }}</a> ha solicitado conectarse contigo.</strong>
                            <p class="fecha" title="Fecha de la solicitud">{{ solicitud['fecha_solicitud'] }}</p>
                        </div>
                        <form action="{{ url_for('notificaciones.responder_solicitud', id_vinculacion=solicitud['id_vinculacion']) }}" method="POST">
                            <button name="respuesta" value="aceptar" type="submit" title="Aceptar solicitud de conexión">Aceptar</button>
                            <button name="respuesta" value="rechazar" type="submit" title="Rechazar solicitud de conexión">Rechazar</button>
                        </form>
                    </li>
                </ul>
            {% endfor %}
        
            {% for notificacion in notificaciones %}
                <ul class="notificacion" title="Notificación recibida">
                    <li class="{% if notificacion['leida'] %}leida{% else %}no-leida{% endif %}" data-aos-delay="300">
                        <h3 title="Notificación"><i class='bx bxs-bell' title="Icono de notificación"></i> Notificación</h3>
                        <div class="message" title="Mensaje de notificación">
                            <strong title="Mensaje recibido">{{ notificacion['mensaje'] }}</strong>
                            <p class="fecha" title="Fecha de la notificación">{{ notificacion['fecha'] }}</p>
                        </div>

                        {% if notificacion.get('id_entrenamiento') %}
                            <div class="notificacion-container">
                                <a class="btn-notificacion-entrenamiento" href="/entrenamiento/rutina/{{ notificacion['id_entrenamiento'] }}" title="Ir al entrenamiento relacionado">
                                    Ir a Entrenamiento
                                </a>
                            </div>
                        {% endif %}
                    </li>
                </ul>
            {% endfor %}
        
            {% if not solicitudes and not notificaciones %}
                <p title="No tienes notificaciones pendientes">No tienes notificaciones pendientes.</p>
            {% endif %}
        </div>
    </div>

    <script>
        document.getElementById("tipo").addEventListener("change", function () {
            let criterio = this.value;
            let lista = document.querySelector(".section-notificaction");
            let notificaciones = Array.from(lista.getElementsByClassName("notificacion"));

            if (criterio === "fecha") {
                notificaciones.sort((a, b) => {
                    let fechaA = new Date(a.querySelector(".fecha").textContent.trim());
                    let fechaB = new Date(b.querySelector(".fecha").textContent.trim());
                    return fechaB - fechaA; // Orden descendente (más reciente primero)
                });
            } else if (criterio === "tipo") {
                notificaciones.sort((a, b) => {
                    let esSolicitudA = a.querySelector("h3").textContent.includes("Solicitud de Conexión");
                    let esSolicitudB = b.querySelector("h3").textContent.includes("Solicitud de Conexión");
                    return esSolicitudB - esSolicitudA; // Prioriza solicitudes
                });
            }

            // Vacía y vuelve a insertar en el orden correcto
            lista.innerHTML = "";
            notificaciones.forEach(noti => lista.appendChild(noti));
        });
    </script>

    <script>
        // Manejar cambio en el filtro de orden
        document.getElementById("orden-notificaciones").addEventListener("change", function() {
            const orden = this.value;
            // Recargar la página con el nuevo parámetro de orden
            window.location.href = "{{ url_for('notificaciones.listar_solicitudes') }}?orden=" + orden;
        });

        // Alternativa con AJAX para evitar recargar la página completa
        /*
        document.getElementById("orden-notificaciones").addEventListener("change", async function() {
            const orden = this.value;
            try {
                const response = await fetch(`/notificaciones?orden=${orden}`);
                const html = await response.text();
                
                // Parsear la respuesta y actualizar solo la sección de notificaciones
                const parser = new DOMParser();
                const doc = parser.parseFromString(html, 'text/html');
                const newContent = doc.querySelector('.section-notificaction').innerHTML;
                document.querySelector('.section-notificaction').innerHTML = newContent;
            } catch (error) {
                console.error('Error al cambiar el orden:', error);
            }
        });
        */
    </script>

{% endblock %}